package org.example.PKExamplesOfClass.Inner;

// Abstract Example
abstract class AAbstractClass {
    abstract void aMethod();
}

// Interface Example
interface Runable {
    void run();
}

public class AnonymousInnerClass {
    public static void main(String args[]) {
        // Abstract Example
        AAbstractClass aac = new AAbstractClass() {
            void aMethod() {
                System.out.println("This method is run by abstract class");
            } // overloading
        };
        aac.aMethod();

        // Interface Example
        Runable aRunable = new Runable() {
            public void run() {
                System.out.println("This method is run by interface");
            }
        };
        aRunable.run();
    }
}

// Internal class generated by the compiler
/*
import java.io.PrintStream;
// For Abstract
static class AnonymousInnerClass$1 extends AAbstractClass
{
    AnonymousInnerClass$1(){}
    void aMethod()
    {
        System.out.println("This method is run by abstract class");
    }
}

// For Interface
static class AnonymousInnerClass$1 implements Runable
{
AnonymousInnerClass$1(){}
void run(){System.out.println("This method is run by interface");
}
/**/