package org.example.PKExamplesOfClass.Inner;

interface ShowableInterfaceInInterface {
    void show();

    interface Message {
        void msg();
    }
}
class ShowableClassInInterface {
    interface Message {
        void msg();
    }
}
interface ShowableInterfaceInClass {
    class InnerClass {
        InnerClass (){
            System.out.println("This is Showable Interface In Class");
        }
    }
}
public class InterfaceNestedClassOrInterface
        extends ShowableClassInInterface
        implements ShowableInterfaceInInterface.Message, ShowableClassInInterface.Message {
    public void msg() {
        System.out.println("This is nested interface, class");
    }

    public static void main(String args[]) {
        ShowableInterfaceInInterface.Message sIIMessage = new InterfaceNestedClassOrInterface();//upcasting here
        sIIMessage.msg();
        ShowableClassInInterface.Message sCIMessage = new InterfaceNestedClassOrInterface();//upcasting here
        sCIMessage.msg();
        ShowableInterfaceInClass.InnerClass sICMessage = new ShowableInterfaceInClass.InnerClass();
    }
}

// Internal class generated by the compiler
/*
// For nested interface which is declared within the interface
public static interface Showable$Message
{
    public abstract void msg();
}
*/