package org.example.PKExamplesOfClass.Inner;

public class LocalInnerClass {
    private int aVariable = 10;//instance variable

    void runMethod() {
        int aLocalVariable = 10;//local variable must be final till jdk 1.7 only
        class Local {
            void msg() {
                System.out.println(aVariable + aLocalVariable);
            }
        }
        Local l = new Local();
        l.msg();
    }

    public static void main(String args[]) {
        LocalInnerClass obj = new LocalInnerClass();
        obj.runMethod();
    }
}

// Internal class generated by the compiler
/*
import java.io.PrintStream;
class LocalInnerClass$Local
{
    final LocalInnerClass this$0;
    LocalInnerClass$Local()
    {
        super();
        this$0 = Simple.this;
    }
    void msg()
    {
        System.out.println(LocalInnerClass.access$000(LocalInnerClass.this));
    }
}
/**/