package org.example.PKExamplesOfClass.Inner;

public class StaticNestedClass {
    static int aVariable = 10;

    static class Inner {
        void msg() {
            System.out.println(aVariable);
        }
    }

    static class StaticInner {
        static void msg() {
            System.out.println(aVariable);
        }
    }

    public static void main(String args[]) {
        StaticNestedClass.Inner obj = new StaticNestedClass.Inner();
        obj.msg();
        StaticNestedClass.StaticInner.msg();//no need to create the instance of static nested class
    }
}

// Internal class generated by the compiler
/*
import java.io.PrintStream;

static class StaticNestedClass$Inner {
    StaticNestedClass$Inner() {
    }

    void msg() {
        System.out.println((new StringBuilder()).append(aVariable)
                .append(StaticNestedClass.aVariable).toString());
    }
}
*/